version: '3.8'

services:
  rabbitMq:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=springEcommerce
    restart: always
